services:
  # Database backend
  postgres-server:
    image: postgres:16-alpine
    container_name: postgres-server
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - zabbix-net
    restart: always

  # Zabbix Server
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-7.4-latest
    container_name: zabbix-server
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: postgres-server
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - zbx_server_alertscripts:/usr/lib/zabbix/alertscripts
      - zbx_server_externalscripts:/usr/lib/zabbix/externalscripts
    depends_on:
      - postgres-server
    networks:
      - zabbix-net
    restart: always

  # Zabbix Frontend Web Interface
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-7.4-latest
    container_name: zabbix-web
    ports:
      - "8080:8080"
    environment:
      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}
      DB_SERVER_HOST: postgres-server
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PHP_TZ: "UTC"
    depends_on:
      - postgres-server
      - zabbix-server
    restart: always
    networks:
      - zabbix-net

  fmc-collector:
    build:
      context: .
    container_name: fmc-collector
    environment:
      FMC_URL: ${FMC_URL}
      FMC_USER: ${FMC_USER}
      FMC_PASSWORD: ${FMC_PASSWORD}

    volumes:
      - ./data:/data
    networks:
      - zabbix-net
    restart: unless-stopped

volumes:
  pg_data:
  zbx_server_alertscripts:
  zbx_server_externalscripts:

networks:
  zabbix-net:
    driver: bridge